# Numpy Einführung


In [1]:
import numpy as np

## Erstellen eines Numpy Arrays


In [ ]:
import numpy as np
# Die Elemente eines Numpy nd-Arrays sollten immer vom selben Datentyp sein

# python listen
list_1 = ["a", "b", "c", "d"]
list_2 = [1, 2, 3, 4, 5]
list_3 = [False, False, False, True, 1]

# creacion/generacion de NumPy array
list_1NP = np.array(list_1)
list_2NP = np.array(list_2)
list_3NP = np.array(list_3)

### Array Dimension, Shape, Datentyp und Size


In [ ]:
# Array-Dimension, Shape, Datentyp und Size

# Dimension    # Shape         # Daten Type    # Len
list_1NP.ndim, list_1NP.shape, list_1NP.dtype, list_1NP.size

(1, (4,), dtype('<U1'), 4)

In [11]:
list_2NP.ndim, list_2NP.shape, list_2NP.dtype, list_2NP.size

(1, (5,), dtype('int64'), 5)

In [ ]:
# Ein Array mit Integer und Floats. Numpy bildet alle Werte als float64 Bit ab

list_4NP = np.array([1, 2, 3, 4, 5, 5.5])
list_4NP.dtype

dtype('float64')

## Vektoren

Ein Vektor ist ein mathematisches Objekt, das sowohl eine Richtung als auch eine Magnitud (Länge) besitzt. Vektoren werden oft genutzt, um Punkte in einem Raum relativ zu einem anderen Punkt zu beschreiben.

#### Spaltenvektor (m × 1-Matrix)

Ein Spaltenvektor ist eine Matrix mit genau einer Spalte
$
 \vec{e}_1= \left(\begin{array}{c} 1 \\ 0 \\ 1 \end{array}\right)
$

#### Zeilenvektor ( 1 × n-Matrix)

(Numpy Arrays sind per default Zeilenvektoren)  
da ein Zeilenvektor die transponierte form eines Spaltenvektors ist, tragen sie das T im Namen:  
$
 \vec{x}{^T} = (x \; y \; z) 
$


## Matrizen

Eine Matrix ist eine rechteckige Anordnung von Zahlen, Symbolen oder Ausdrücken, die in Zeilen und Spalten organisiert ist. Sie wird verwendet, um Daten kompakt darzustellen und erleichtert Berechnungen in Bereichen wie Algebra, Physik, Informatik und maschinellem Lernen.

Eine 2x3 Matrix würde mathematisch so notiert werden:

$ M = \left( \begin{matrix} 1 & 2 & 3 \\ 3 & 4 & 4 \end{matrix} \right) $


In [63]:
# Dimension und Shape eines 2-dimensionales Arrays. shape(2, 3) bedeutet: 2 Reihen, 3 Spalten

# vectores seran representados con v -minuscula-
# ferture-Vektor  [age, cm, kg]
vector = np.array([43, 178, 78])
print("(v) -> vector: ", vector, type(vector), vector.shape)

# Matrices seran representadas con M -mayuscula-
Matrix = np.array([[1, 2, 3], [4, 5, 6]])

print("(M) -> Matrix: ", Matrix.shape, Matrix.size)


(v) -> vector:  [ 43 178  78] <class 'numpy.ndarray'> (3,)
(M) -> Matrix:  (2, 3) 6


## Axis - der Achsenbegriff

In NumPy beschreibt der Begriff axis die Dimension, entlang der Operationen in einem Array ausgeführt werden, wobei axis 0 für Zeilen, axis 1 für Spalten und höhere Achsen (z. B. axis 2, axis 3) für weitere Dimensionen wie Tiefe oder Zeit in mehrdimensionalen Arrays stehen.

![title](numpy-arrays-have-axes.webp)


## Arrays erstellen


### Array mit gemischten Datentypen int und float


In [16]:
M = np.array([1.1, 2.2, 4, 2])
M

array([1.1, 2.2, 4. , 2. ])

### Array mit Python - Objekten (Datentyp object)


In [ ]:
# Python Objekte (EJEMPLO MALO), no deberia hacerse con NumPy

M = np.array([[1, 2], 1, {"a": 1}], dtype="object")
M.dtype, M[2]

(dtype('O'), {'a': 1})

### Explizit Datentyp beim Erstellen des Arrays angeben


In [ ]:
# dtype (aca sera float32 bit als -->DATENTYP)
M = np.array([12, 53, 53.3], dtype="float32")  # como string
M = np.array([12, 53, 53.3], dtype=np.float32)  # como np.Valor
M.dtype

dtype('float32')

### Null Matrix (intrinsic numpy array)

#### 2 x 2 Null-Matrix

$ \left( \begin{matrix} 0 & 0 \\ 0 & 0 \end{matrix} \right) $


In [ ]:
# Nullmatrix
N = np.zeros(shape=(2, 2), dtype="int8")
N, N.dtype

(array([[0, 0],
        [0, 0]], dtype=int8),
 dtype('int8'))

In [ ]:
# eindimensionale Null-Matrix und Datentyp int32
N = np.zeros(shape=(2,), dtype="int32")  # 2 elementos
N, N.dtype

(array([0, 0], dtype=int32), dtype('int32'))

In [33]:
# dreidimensionale Null-Matrix
N = np.zeros(shape=(1, 2, 1, 2), dtype="int32")
N, N.dtype, N.ndim

(array([[[[0, 0]],
 
         [[0, 0]]]], dtype=int32),
 dtype('int32'),
 4)

## Einheitsmatrix

Eine spezielle Form ist die n × n-Einheitsmatrix, welche eine `Diagonalmatrix ist, deren Hauptdiagonalelemente alle gleich 1 sind`.

Die Einheitsmatrix wird mit E bezeichnet.

#### Einheitsmatrix 3. Ordnung

$ E = \left( \begin{matrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{matrix} \right) $


In [35]:
# Identitätsmatrix
M = np.identity(4)
M

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Matrix mit Default-Werten

$ M = \left( \begin{matrix} 42 & 42 & 42 \\ 42 & 42 & 42 \\ 42 & 42 & 42 \end{matrix} \right) $


In [ ]:
# 3 x 3 Matrix mit Defaultwerten
np.full(shape=(3, 3), fill_value=42)

array([[42, 42, 42],
       [42, 42, 42],
       [42, 42, 42]])

## Diagonal-Matrix

Als m × n-Diagonalmatrix D = (dij) wird eine Matrix bezeichnet, deren Elemente
außerhalb der Hauptdiagonale Null sind, bei der also gilt: dij = 0 für alle i ≠ j

#### 3 x 3 Diagonalmatrix

$\left( \begin{array}{rrrr}
2 & 0 & 0 \\
0 & 3 & 0 \\
0 & 0 & 1 \\
\end{array} \right) $


In [ ]:
# Diagonal-Matrix
M = np.diag([2, 3, 1])

M, M.diagonal()

(array([[2, 0, 0],
        [0, 3, 0],
        [0, 0, 1]]),
 array([2, 3, 1]))

## Reihe anlegen mit Range

Wir können mit Numpy ählich wie der range-Funktion aus Python auch eine Reihe anlegen. Dazu können wir die numpy-Methode `arange` nutzen, die identisch zur range-Funktion die drei Parameter Start, Stop (exklusive) und Schrittweite hat. Stop ist dabei wieder exclusive (wie bei range).

Mit arange erstellte Arrays sind stehts eindimensional, haben also den Shape (n, ).


In [44]:
# arange(start, stop, step)

my_range = np.arange(0, 11, 2)
my_range, my_range.shape

(array([ 0,  2,  4,  6,  8, 10]), (6,))

## Intervall anlegen mit linspace

mit der Numpy-Methode `linspace` lässt sich einfach ein Intervall anlegen. Wichtige Argumente sind hier `endpoint`, das angibt, ob das Interval halboffen sein soll und `num`, dass die Anzahl der gleichgroßen Werte zwischen den Intervall-Grenzen angibt, d.h. die Abstände der Punkte sind gleichgroß. Defaultwert für num ist 50.


In [45]:
# halboffenes Intervall zwischen 1 und 5 mit 20 Werten
i = np.linspace(1, 5, num=20, endpoint=False)
i

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [46]:
# geschlossenes Intervall zwischen 1 und 5 mit 20 Werten
i = np.linspace(1, 5, num=20)
i


array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

## Datentypen

NumPy bietet eine Vielzahl von Datentypen, die auf numerische Berechnungen und Speicheroptimierung ausgelegt sind. Diese Typen sind feiner abgestuft als in Python selbst.

Jeder Datentyp hat einen bestimmten Wertebereich. Wenn ein Wert diesen Bereich überschreitet, führt das zu Überläufen oder Fehlern.

### Tabelle der NumPy-Datentypen

| Kategorie               | Datentypen                                  | Beschreibung                                           |
| ----------------------- | ------------------------------------------- | ------------------------------------------------------ |
| **Ganzzahlen**          | `int8`, `int16`, `int32`, `int64`           | Ganze Zahlen mit Vorzeichen, 8 bis 64 Bit.             |
| **Positive Ganzzahlen** | `uint8`, `uint16`, `uint32`, `uint64`       | Ganze Zahlen ohne Vorzeichen, 8 bis 64 Bit.            |
| **Gleitkommazahlen**    | `float16`, `float32`, `float64`, `float128` | Zahlen mit Nachkommastellen, 16 bis 128 Bit Präzision. |
| **Komplexe Zahlen**     | `complex64`, `complex128`, `complex256`     | Komplexe Zahlen (Real- und Imaginärteil als Float).    |
| **Boolesche Werte**     | `bool_`                                     | Wahr oder Falsch (`True`, `False`).                    |
| **Zeichenketten**       | `str_`                                      | Unicode-Zeichenketten (beliebige Länge).               |
| **Bytes**               | `bytes_`                                    | Zeichenketten in Byte-Darstellung.                     |
| **Gemischte Typen**     | `object`                                    | Beliebige Python-Objekte.                              |
| **Zeitangaben**         | `datetime64`, `timedelta64`                 | Datums- und Zeitangaben (z. B. für Zeitdifferenzen).   |


In [47]:
for dtype in np.sctypeDict.values():
    print(dtype)

<class 'numpy.bool'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.longdouble'>
<class 'numpy.complex64'>
<class 'numpy.complex128'>
<class 'numpy.clongdouble'>
<class 'numpy.bytes_'>
<class 'numpy.str_'>
<class 'numpy.void'>
<class 'numpy.object_'>
<class 'numpy.datetime64'>
<class 'numpy.timedelta64'>
<class 'numpy.int8'>
<class 'numpy.int8'>
<class 'numpy.uint8'>
<class 'numpy.uint8'>
<class 'numpy.int16'>
<class 'numpy.int16'>
<class 'numpy.uint16'>
<class 'numpy.uint16'>
<class 'numpy.intc'>
<class 'numpy.uintc'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.uint32'>
<class 'numpy.uint32'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.uint64'>
<class 'numpy.uint64'>
<class 'numpy.int64'>
<class 'numpy.uint64'>
<class 'numpy.float64'>
<class 'numpy.complex128'>
<class 'numpy.float32'>
<class 'numpy.complex64'>
<class 'numpy.float16'>
<class 'numpy.bool'>
<class 'numpy.int64'>
<class 'numpy.uint64'>
<class 'numpy.float6

Ein klassisches Problem tritt auf, wenn eine Zahl den zulässigen Bereich eines Datentyps überschreitet.
Zum Beispiel tritt hier ei nOutofbounds-Fehler auf, da die Zahl 24223243 nicht in einen 16bit-Speicher passt.


In [58]:
# Zahl zu groß für 16Bit-Speicher
value = 24223
overflow = np.array([value], dtype=np.int16)
overflow

array([24223], dtype=int16)

## Konvertierung Datentypen

Die Methode astype in NumPy wird verwendet, um den Datentyp eines Arrays zu ändern.
ie erstellt ein neues Array mit dem gewünschten Typ, ohne das ursprüngliche Array zu ändern.

new_array = array.astype(dtype)


In [ ]:
# Float Array nach int konvertieren

float_array = np.array([1.2, 4.9])
int_array = float_array.astype("int8")
float_array, int_array

# ------------------------------------------------


# Übungsaufgaben

1. Erstelle eine 2 x 3 Matrix D mit beliebigen Werten
2. Erstelle ein geschlossenes Interval zwischen 1 und 20 mit 70 Werten
3. Erstelle eine Diagonalmatrix M mit den Werten 4, 2, 8, 1 auf der Diagonalen
4. Betrachte die Diagonale von M und konvertiere diesen Vektor nach uint16

Erstelle für jede Aufgabe eine neue Zelle.


In [73]:
# 1) Erstelle eine 2 x 3 Matrix D mit beliebigen Werten
D = np.array([[1, 3, 5], [2, 4, 6]])
D

array([[1, 3, 5],
       [2, 4, 6]])

In [74]:
# 2) Erstelle ein geschlossenes Interval zwischen 1 und 20 mit 70 Werten
i = np.linspace(1, 20, num=70)
i

array([ 1.        ,  1.27536232,  1.55072464,  1.82608696,  2.10144928,
        2.37681159,  2.65217391,  2.92753623,  3.20289855,  3.47826087,
        3.75362319,  4.02898551,  4.30434783,  4.57971014,  4.85507246,
        5.13043478,  5.4057971 ,  5.68115942,  5.95652174,  6.23188406,
        6.50724638,  6.7826087 ,  7.05797101,  7.33333333,  7.60869565,
        7.88405797,  8.15942029,  8.43478261,  8.71014493,  8.98550725,
        9.26086957,  9.53623188,  9.8115942 , 10.08695652, 10.36231884,
       10.63768116, 10.91304348, 11.1884058 , 11.46376812, 11.73913043,
       12.01449275, 12.28985507, 12.56521739, 12.84057971, 13.11594203,
       13.39130435, 13.66666667, 13.94202899, 14.2173913 , 14.49275362,
       14.76811594, 15.04347826, 15.31884058, 15.5942029 , 15.86956522,
       16.14492754, 16.42028986, 16.69565217, 16.97101449, 17.24637681,
       17.52173913, 17.79710145, 18.07246377, 18.34782609, 18.62318841,
       18.89855072, 19.17391304, 19.44927536, 19.72463768, 20.  

In [75]:
# 3) Erstelle eine Diagonalmatrix M mit den Werten 4, 2, 8, 1 auf der Diagonalen
M = np.diag([4, 2, 8, 1])
M.diagonal()
M

array([[4, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 1]])

In [76]:
# 4) Betrachte die Diagonale von M und konvertiere diesen Vektor nach uint16
v_diag = M.diagonal().astype(np.uint16)