In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Arrays indexieren

Wir können auf Elemente eines Numpy Arrays ebenso wie in Python-Listen (oder Arrays aus anderen Programmiersprachen) per Index zugreifen. Auf das letzte Element können wir mit -1 zugreifen, wie wir das auch von Python-Listen gewohnt sind.

## Indizieren von eindimensionalen Arrays


In [2]:
import numpy as np

M = np.array([1, 2, 3, 4])
M[0], M[-1], M[:2]

(np.int64(1), np.int64(4), array([1, 2]))

## Indizieren von zweidimensionalen Arrays (Matrizen)

Um ein Elment in einer Matrix zu indizieren, können wir mit dem Format `row,column` arbeiten.


In [3]:
import numpy as np

M = np.diag([1, 2, 3])
print(M)
print("elemento en primera Fila, primera columna", M[0, 0])
# alternative
print("elemento en primera Fila, primera columan(alternativa)", M[0][0])

N = M.copy()
N[0][0] = 42
print("N", N)
print("M", M)


[[1 0 0]
 [0 2 0]
 [0 0 3]]
elemento en primera Fila, segunda Fila 1
elemento en primera Fila, segunda Fila(alternativa) 1
N [[42  0  0]
 [ 0  2  0]
 [ 0  0  3]]
M [[1 0 0]
 [0 2 0]
 [0 0 3]]


## Integer array indexing

Wir können beim Indexing auch einen Array mit Index-Positionen angeben


In [4]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(M)
# Element in Zeile 1 und Spalte 3 indizieren (klassisch)
print("e en F1 & C3", M[0][2])

# 1 Zeile und dritte Zeile mit Array Indexing
print("F1 & C3", M[0, 2])

# 1 Zeile und dritte Zeile mit Array Indexing
print(M[[0, 2]][:, [0, 2]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
e en F1 & C3 3
F1 & C3 3
[[1 3]
 [7 9]]


## Aufgabe

- Erstelle eine 2 x 3 Matrix M.
- Gebe den Shape des Arrays aus.
- Gebe den Wert in der zweiten Zeile und der ersten Spalte aus
- Gebe den Datentyp des Arrays aus
- Gebe die 2. Reihe aus (Index 1)

$ M = \left( \begin{matrix} 1 & 12 & 13 \\ 42 & 51 & 62 \end{matrix} \right) $


In [5]:
# Aufgabe: 5 Minuten Zeit
M = np.array([[1, 12, 13], [42, 51, 62]])

shape = M.shape
wert = M[1, 0]
date_type = M.dtype
reihe = M[1]

print("M:\n", M)
print("--------")
print("SHAPE:", shape)
print("--------")
print("WERT:", wert)
print("--------")
print("TYP:", date_type)
print("--------")
print("Reihe:", reihe)


M:
 [[ 1 12 13]
 [42 51 62]]
--------
SHAPE: (2, 3)
--------
WERT: 42
--------
TYP: int64
--------
Reihe: [42 51 62]


# Arrays Slicing (Ausschneiden von Werten aus Arrays)

Generell erzeugen Slicing Operationen in Numpy keinen neuen Array, sondern bieten einen sogenannten View auf das Ursprungsarray. verändert man die geslicte Submenge, verändert man auch die Originaldaten. Verhindern kann man das mit copy (siehe weiter unten).

## von eindimensionalen Arrays (Vektoren)

Eindimensionale Arrays lassen sich wie in Python mit dem Slicing-Operator sclicen. Schema `Start:End:Schrittweite`.


In [6]:
import numpy as np

normale_liste = [1, 2, 3]
normale_liste[0:2]  # normale Sequenz-slicing

x = np.array([1, 2, 3, 4, 5, 6])
x[0:2]  # entspricht .Py Slicing

array([1, 2])

## von zweidimensionalen Arrays (Matritzen)

Zweidimensionale Arrays lassen sich wie in Python mit dem Slicing-Operator sclicen.
Schema `Zeile von:Zeile bis, Spalte von:Spalte bis`.


$ M = \left( \begin{matrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{matrix} \right) $


In [7]:
M = np.array([[1, 2, 3], [4, 5, 6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

### alle Zeilen, die ersten beiden Spalten

Um eine Matrix nach folgendem Schema aus M "auszuschneiden"
$ M = \left( \begin{matrix} 1 & 2 \\ 4 & 5 \end{matrix} \right) $


In [8]:
M = np.array([[1, 2, 3], [4, 5, 6]])
# alle Zeilen (:), die ersten beiden Spalten : 0:2 (el 2 es exclusivo)
M[:, :2]

array([[1, 2],
       [4, 5]])

### ersten zwei Zeilen, erste Spalte


In [9]:
M = np.array([[1, 2, 3], [4, 5, 6]])
#  (Slicing der ersten beiden Zeilen, Indexing der Spalte 0)
M, M[0:2, 0:1]

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1],
        [4]]))

### alle Zeilen und die erste und dritte Spalte mit Multiindexing


In [10]:
M = np.array([[1, 2, 3], [4, 5, 6]])
# alle Zeilen und die erste und dritte Spalte mit Multiindexing
"M: ", M, "R: ", M[:, [0, 2]]

('M: ',
 array([[1, 2, 3],
        [4, 5, 6]]),
 'R: ',
 array([[1, 3],
        [4, 6]]))

### Diagonale aus zweidimensionalem Array


In [11]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Diagonale
M.diagonal()

print("M", M)

M [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Aufgabe

$X = \left( \begin{array}{rrrr}
2 & 3 & 8 \\
1 & 22 & 22 \\
4 & 22 & 22 \\
\end{array} \right) $

a) Erstelle das zweidimensionale Array  
b) Schneide den Block mit den 22 aus (2 x 2 Matrix)  
c) Schneide die diagonalen Werte aus (als Vektor mit shape(3,) [2, 22, 22])
d)


In [ ]:
import numpy as np
# Happy Coding: 5 Minuten Zeit

# a
X = np.array([[2, 3, 8], [1, 22, 22], [4, 22, 22]])

# b
block = X[1:, 1:]

# c
diag = X.diagonal()

print("X: ", "\n", X)
print("Diag: ", diag, "Shape: ", diag.shape)


X:  
 [[ 2  3  8]
 [ 1 22 22]
 [ 4 22 22]]
Diag:  [ 2 22 22] Shape:  (3,)


## copy

Um eine tatsächliche Kopie durch Slicing von einem Array zu erstellen, muss man die Methode Copy nutzen


In [13]:
# ohne copy: Verändern von Index 0 bei P_copy verändert auch P
P = np.array([[1, 2, 3], [4, 5, 6]])
P_copy = P[:, 2].copy()
P_copy[0] = 100
"P: ", P, "COPY: ", P_copy, "BASE: ", P_copy.base

('P: ',
 array([[1, 2, 3],
        [4, 5, 6]]),
 'COPY: ',
 array([100,   6]),
 'BASE: ',
 None)

In [14]:
# mit copy: Z bleibt unverändert
...