## Array Reshaping

wie lässt sich mit Reshaping der shape eines Arrays verändern?

## Was ist ein Shape?

Der Shape ist die Dimensionsgröße unseres Arrays. Eine Matrix in der folgenden Form hätte einen Shape von (2, 3)

$ M = \left( \begin{matrix} 1 & 2 & 3 \\ 3 & 4 & 4 \end{matrix} \right) $

Der Shape liegt also in der Form Zeilen x Reihen vor.

Um jetzt die Dimensionsgröße eines Arrays zu ändern, kann man es Reshapen. Um aus einem eindimensionalen Array M (erstellt mit der Methode `arange`) mit dem Shape (9,) ein zweidimensionales Array mit dem Shape (3,3) zu machen, gehen wir wie folgt vor.

`Ein Shape wird immer in Form eines Tupels dargestellt.` Ein Tupel mit nur einem Element ist zum Beispiel (3,), wobei die Klammer auch weggelassen werden kann, wenn es sich um kein Funktionsargument handelt.


In [ ]:
import numpy as np

M = np.arange(1, 10)
print(M)
print(M.shape)

# 1 x 9 Array mit 9 Werten erstellen und Shape anzeigen

In [11]:
# Reshapen auf Shape (3,3)
M = M.reshape((3, 3))
print(M)
print("Shape: ", M.shape)
print("ndim: ", M.ndim)

## Wann kann ich ein Array reshapen?

Das geht nur, wenn die angegebene Dimensionsgröße möglich ist. Ein Array mit 8 Elementen kann nicht auf den Shape (3,3) gebracht werden, weil die Anzahl der Elemente so einen Shape nicht zulässt.

`Vereinfacht gesagt: wenn das Produkt von Zeilen und Spalten des Zielshapes nicht der Anzahl der aktuellen Elementen entspricht, ist ein Reshaping nicht möglich.`


In [22]:
# Array mit 8 Werten erstellen
M = np.arange(1, 9, 1)
# error esperado 8 no caben bien en 3x3
M = M.reshape((3, 3))


ValueError: cannot reshape array of size 8 into shape (3,3)

## Zweidimensionales Array auf eindimensional Shapen

Ein Array mit dem Shape (4, 2), also 4 Zeilen und 2 Spalten enthält 8 Elemente. Folglich lässt sich mit einem Reshape auf (1, 8) ein eindimensionales Array erstellen.


In [8]:
# zweidimensionales Zufallsarray erstellen
np.random.seed(42)
Z = np.random.randint(low=2, high=8, size=(4, 2), dtype="int32")

print(Z)
X_shaped = Z.reshape(1, 8)
Y_shaped = Z.reshape(8, 1)
print("X: ", X_shaped)
print("Y: ", Y_shaped)


[[5 6]
 [4 6]
 [6 3]
 [4 4]]
X:  [[5 6 4 6 6 3 4 4]]
Y:  [[5]
 [6]
 [4]
 [6]
 [6]
 [3]
 [4]
 [4]]


## aus einem Zeilenvektor einen Spaltenvektor machen

eindimensionale Listen und Numpy-Arrays kommen der math. Sicht eines Zeilenvektors am nächsten. Ein Zeilenvektor zeichnet sich dadurch aus, dass er nur eine Zeile (und viele Spalten) hat.

Ein Spaltenvektor wiederum hat nur eine Spalte, aber viele Zeilen. Das Numpy-Konstrukt, dass dem Spaltenvektor am nächsten kommt, ist ein zweidimensionales Array mit Listen der Länge 1.

Durch das Numpy-Keywort `np.newaxis` erstellen wir eine neue "leere" Dimension an der Stelle, wo wir es einsetzten.


In [14]:
v = np.array([1, 3, 5, 6])
print("v: ", v)
print("v shape: ", v.shape)


v:  [1 3 5 6]
v shape:  (4,)


## ein mehrdimensionales Array flatten

die Methode `ravel` bringt ein mehrdimensionales Array auf eine Dimension und erzeugt einen View auf die Originaldaten. Es gibt auch noch eine identische Funktions namens `flatten`, die allerdings eine echte Kopie erzeugt. Je nach Anwendungsfall sollte man also wählen.


In [ ]:
np.random.seed(42)
Z = np.random.randint(low=2, high=8, size=(4, 2, 2), dtype="int32")
print(Z)
Z_ravel = Z.ravel()  # das ist eine View
print(Z_ravel)
Z_flatten = Z.flatten()  # Kopie
print(Z_flatten)


## Automatisches Reshaping

Oft hat man den Fall, dass man ein Array Reshapen muss, aber nur von einer Dimension den Shape kennt. Der zweite müsste also berechnet werden, um das Reshaping valide zu gestalten.

Dafür gibt es ein Features namens `Automatic Reshaping`, bei dem anstelle der wirklichen Dimension einfach eine `-1` eingetragen wird. Numpy berechnet dann selbst den benötigten Wert, falls das möglich ist. Das geht nur für eine unbekannte Dimension


In [ ]:
np.random.seed(42)
Z = np.random.randint(low=2, high=8, size=(4, 2), dtype="int32")
print(Z)

Z_shaped = Z.reshape(2, -1)
print(Z_shaped)

v = np.array([1, 9, 1])


# Reshapen auf (2,x)

# Aufgabe: Reshaping von NumPy-Arrays

## Problemstellung:

Du arbeitest mit Daten, die in einer eindimensionalen Liste gespeichert sind. Für eine bessere Analyse möchtest du diese Daten in unterschiedliche Formen (2D, 3D) umwandeln.

---

## Aufgabe:

1. **Gegeben ist ein eindimensionales NumPy-Array** mit den Zahlen von 1 bis 12 (inklusive).
2. **Forme das Array** in die folgenden Strukturen um:
   - Ein **2D-Array** mit 3 Zeilen und 4 Spalten.
   - Ein **3D-Array** mit den Dimensionen (2 x 2 x 3).
3. **Überprüfe die Shapes** der neu geformten Arrays, um sicherzustellen, dass sie korrekt sind.
4. **Zeige die Arrays** mit `print()`.

---

### Hinweis:

Verwende die Methode `reshape()` von NumPy, um das Array in die gewünschte Form zu bringen. Du kannst `array.reshape(rows, columns)` aufrufen, um das Array umzuformen.


In [13]:
# Happy Coding! Zeit, 5 Minuten
import numpy as np

v1 = np.arange(1, 13)
D2 = v1.reshape((3, 4))
D3 = v1.reshape((2, 2, 3))
shape_D2 = D2.shape
shape_D3 = D3.shape

print("1: ", v1)
print("+-------------+")
print("2a: ", D2)
print("+-------------+")
print("2b: ", D3)
print("+-------------+")
print("Shape/3a: ", shape_D2)
print("+-------------+")
print("Shape/3b: ", shape_D3)

1:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
+-------------+
2a:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
+-------------+
2b:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
+-------------+
Shape/3a:  (3, 4)
+-------------+
Shape/3b:  (2, 2, 3)


In [ ]:
# Reshape
M2D = v1  # ?
M3D = v1  # ?

# Aufgabe 2: 1D-Daten zu 2D Input für ML

Beschreibung: In vielen Machine-Learning-Modellen erwartet das Modell die Eingabedaten als eine 2D-Array (n_samples, n_features).
Du hast n Datenpunkte (Features), die aktuell als ein Vektor vorliegen (1D).

Reshape die Daten zu einem 2D-Array mit einem Sample und n Features.


In [21]:
import numpy as np

# Gegebene 1D-Daten
n = 10
data = np.arange(n)  # [0, 1, 2, ..., 9]
print("data:", data)
print("data_Shape:", data.shape)
print("+-------------+")

# TODO: Reshape die Daten zu einem 2D-Array mit (1, n_features)
reshaped_data = data.reshape(1, n)
print("Reshaped Data:", reshaped_data)
print("Shape:", reshaped_data.shape)

data: [0 1 2 3 4 5 6 7 8 9]
data_Shape: (10,)
+-------------+
Reshaped Data: [[0 1 2 3 4 5 6 7 8 9]]
Shape: (1, 10)


#### Erwartete Ausgabe

Reshaped Data:
[[0 1 2 3 4 5 6 7 8 9]]

Shape: (1, 10)
