# Numpy Arrays verbinden
Para formar una nueva matriz común de dos o más matrices, disponemos de varias opciones.


## Concatenate de matrices monodimensionales y multidimensionales
El método P0 permite conectar matrices de una y de varias dimensiones a un array. Aquí es importante entender el término de eje (axis). Axis 0 designa las filas (rows), mientras que axis 1 designa las columnas.

**Generell se puede decir que el shape del nuevo array sólo cambia en el eje en el que se unen los arrays**.

**Sólo se pueden contagiar los mismos shapes (igual dimensión) de matrices en el eje de no-concatenación**


- axis=0 (Zeilenweise Konkatenation) → Spaltenzahl muss gleich sein.       
- axis=1 (Spaltenweise Konkatenation) → Zeilenzahl muss gleich sein. 

![title](numpy-arrays-have-axes.webp)

## Concatenate von zwei zweidimensionalen Arrays an Axis 0
Cuando realizamos concatenate en matrices con axis=0, los arrays se agrupan "entrelazados," lo que significa que el shape de las columnas (columnas) sigue siendo el mismo, pero cambia de línea. Por lo tanto, los arrays se "apilan" verticalmente. Para ello, el número de columnas en ambas matrices debe coincidir. El shap en el eje 0 ha cambiado, el arnés de columna sigue siendo igual.

![title](explanation_numpy-concatenate-axis-0.webp)

In [12]:
import numpy as np

arr1 = np.array([[1, 1, 1], [1, 1, 1]])
arr2 = np.array([[9, 9, 9], [9, 9, 9], [9, 9, 9]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)


## Pero: combinar 2 matrices monodimensionales en un array en el eje 0 con concatentete

Dado que los arrays unidimensionales solo tienen un eje, la conexión al eje 0 conduce a otro array monodimensional. El shape en lugar de 0 ha cambiado.

In [13]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])


## Aufgabe
Se dan vector v con 3 elementos y 2 x 3 matriz M. Conecta los dos objetos en el eje 0 (filas) a una nueva matriz A.

Recordatorio: sólo se pueden concatenar arrays que tengan la misma shape en el eje NO-Concatenación (aquí eje 1). Formas v antes de la concatenación en consecuencia.

El resultado debería ser así:

[[ 1  2  3]   
 [11 22 33]   
 [44 55 66]]    

In [3]:
# Happy Coding (5 Minuten)
import numpy as np
v = np.array([1, 2, 3])
M = np.array([[11, 22, 33], [44, 55, 66]])
print("1", v)
v = v.reshape(-1, 3)
print("2", v)
A = np.concatenate((v, M), axis=0)

print(A)

1 [1 2 3]
2 [[1 2 3]]
[[ 1  2  3]
 [11 22 33]
 [44 55 66]]


## Concatenate von zwei zweidimensionalen Arrays an Axis 1
Cuando realizamos concatenate con axis=1, los arrays se unen "alternadamente," lo que da lugar a que el shape de las columnas (columnas) cambie, pero el array de fila permanece igual.

In [14]:
arr1 = np.array([[1, 1, 1], [1, 1, 1]])
arr2 = np.array([[9, 9, 9], [9, 9, 9]])

arr3_y = np.concatenate((arr1, arr2), axis=0)
arr3_x = np.concatenate((arr1, arr2), axis=1)

print("Y / axis 0: ", '\n', arr3_y)
print("base Y: ", arr3_y.base)
print("-----------------------------")
print("X / axis 1: ", '\n', arr3_x)
print("base X: ", arr3_x.base)


# alternativa (vstack)
x_st = np.hstack([arr1, arr2])

# alternativa (vstack)
y_st = np.vstack((arr1, arr2))
print("alternativas: ")
print("-----------------------------")
print("vertical / y_st / axis 0: ", '\n', y_st)
print("-----------------------------")
print("horizontal / x_st / axis 1: ", '\n',x_st)
print("-----------------------------")


Y / axis 0:  
 [[1 1 1]
 [1 1 1]
 [9 9 9]
 [9 9 9]]
base Y:  None
-----------------------------
X / axis 1:  
 [[1 1 1 9 9 9]
 [1 1 1 9 9 9]]
base X:  None
alternativas: 
-----------------------------
vertical / y_st / axis 0:  
 [[1 1 1]
 [1 1 1]
 [9 9 9]
 [9 9 9]]
-----------------------------
horizontal / x_st / axis 1:  
 [[1 1 1 9 9 9]
 [1 1 1 9 9 9]]
-----------------------------


## Combinar vector y matriz vía vstack en un array multidimensional
Para conectar los arrays con el ABSP0, deben tener las mismas dimensiones. Por lo tanto, no se puede conectar un array de una o varias dimensiones. Para ello, se utiliza el método ABS P1. vstack significa apilamiento vertical.

En el caso de vstack, sólo debe existir que ambas matrices tengan el mismo número de columnas. Por supuesto, también se pueden conectar dos matrices multidimensionales con vstacke.

In [9]:
arr1 = np.array([1, 1, 1])
arr2 = np.array([[9, 9, 9], [9, 9, 9]])

print(np.vstack((arr1, arr2)))


[[1 1 1]
 [9 9 9]
 [9 9 9]]


## Combinar dos matrices a través de un hack en un array multidimensional
Para conectar los arrays con el ABSP0, deben tener las mismas dimensiones. Por lo tanto, no se puede conectar un array de una o varias dimensiones. Para ello, se utiliza el método ABS P1. hstack significa apilaciones horizontales.

En el caso de vstack, solo debe darse que ambas matrices tienen el mismo número de líneas.

In [20]:
# zwei Arrays mit shape 2,1 und 2,3
arr1 = np.array([[1], [1]])
arr2 = np.array([[9, 9, 9], [9, 9, 9]])


## Aufgabe

## Aufgabe

Una empresa gestiona el inventario de 6 productos en un almacén central y dos sucursales. Los datos del inventario están disponibles como una matriz 1D y están destinados a ser rediseñados para un mejor análisis.

1. Reshape la matriz 1D dada en una matriz 3×6, por lo que cada línea corresponde a una ubicación de almacenamiento (almacén central, filial 1, filial 2).
2. Extraer (slice) de la matriz las existencias de los 3 primeros productos para todas las ubicaciones.
3. Añade nuevos productos para dos nuevas sucursales (3 y 4) a la matriz stock original. Usa vstack. Guarda el resultado en la variable final_stock_matriz.



El resultado de final_stock_matrix se ve así al final:

[[100, 150,  80, 200,  50,  90],     
       [ 60, 120,  70, 100,  30,  50],       
       [ 40, 110,  60,  80,  20,  30],         
       [ 55, 130,  75,  95,  35,  60],         
       [ 45, 100,  65,  85,  25,  40]]

2. El slicing del producto se ve así:

        [[100, 150,  80],     
        [ 60, 120,  70],       
        [ 40, 110,  60]]     

In [2]:
import numpy as np

# 1D-Array mit den Beständen für 3 Standorte (6 Produkte pro Standort)
stock = np.array([100, 150, 80, 200, 50, 90,   # Zentrallager
                  60, 120, 70, 100, 30, 50,    # Filiale 1
                  40, 110, 60, 80, 20, 30])    # Filiale 2

# 1. Reshape in eine 3x6-Matrix (Zeilen: Standorte, Spalten: Produkte)

# 2. Slicing: Extrahiere die ersten 3 Produkte für alle Standorte (Ergebnis wird nicht weiter benötigt)

# 3. Simulierte Lieferung für zwei neue Filialen (2x6-Matrix)
new_delivery = np.array([[55, 130, 75, 95, 35, 60],  # Filiale 3
                         [45, 100, 65, 85, 25, 40]]) # Filiale 4

final_stock_matrix = ...