# Numpy Arrays verbinden
Um aus zwei oder mehreren Arrays einen neuen gemeinsamen Array zu bilden, stehen uns mehrere Möglichkeiten zur Verfügung.



## Concatenate von ein- und mehrdimensionalen Arrays
Mit der Methode `concatenate` lassen sich ein- und mehrdimensionale Arrays zu einem Array verbinden. Wichtig zu verstehen ist hier der Achsenbegriff (axis). Axis 0 bezeichnet die Zeilen (rows), während Axis 1 die Spalten bezeichnet. 

**Generell kann man sagen: Der Shape des neuen Arrays verändert sich nur an der Achse, an dem die Arrays zusammengefügt werden**.

**Es können nur Arrays gleichen Shapes (gleicher Dimension) an der Nicht-Konkatenierungsachse konkateniert werden**


- axis=0 (Zeilenweise Konkatenation) → Spaltenzahl muss gleich sein.       
- axis=1 (Spaltenweise Konkatenation) → Zeilenzahl muss gleich sein. 

![title](numpy-arrays-have-axes.webp)

## Concatenate von zwei zweidimensionalen Arrays an Axis 0
Wenn wir concatenate auf Matrizen mit axis=0 durchführen, werden die Arrays "untereinandert" zusammengefügt. Das führt dazu, dass der Shape der Columns (Spalten) gleich bleibt, sich aber der Zeilenshape verändert. Die Arrays werden also vertikal "gestapelt". Dazu muss die Anzahl an Spalten in beiden Arrays übereinstimmen. Der Shape an Achse 0 hat sich verändert, der Spaltenshape blieb gleich.

![title](explanation_numpy-concatenate-axis-0.webp)

In [17]:
import numpy as np

arr1 = np.array([[1, 1, 1], [1, 1, 1]])
arr2 = np.array([[9, 9, 9], [9, 9, 9], [9, 9, 9]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)


[[1 1 1]
 [1 1 1]
 [9 9 9]
 [9 9 9]
 [9 9 9]]


## Aber: 2 eindimensionale Arrays zu einem Array an der Achse 0 mit concatentate zusammenführen

Da eindimensionale Arrays nur eine Achse haben, führt hier das Verbinden an Achse 0 zu einem weiteren eindimensionalen Array. Der Shape an Stelle 0 hat sich verändert.

In [13]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])


## Aufgabe
Gegeben sind Vektor v mit 3 Elementen und eine 2 x 3 Matrix M.
Verbinde die beiden Objekte an der Achse 0 (Zeilen) zu einer neuen Matrix A.

Erinnerung: es können nur Arrays konkateniert werden, die den gleichen Shape an der NICHT-Konkatenierungsachse (hier Achse 1) haben. Forme v vor der Konkatenierung entsprechend um.

Das Ergebnis sollte so aussehen:

[[ 1  2  3]   
 [11 22 33]   
 [44 55 66]]    

In [18]:
# Happy Coding (5 Minuten)
import numpy as np
v = np.array([1, 2, 3])
M = np.array([[11, 22, 33], [44, 55, 66]])

v = v.reshape(-1, 3)
A = np.concatenate((v, M), axis=0)

print(A)

[[ 1  2  3]
 [11 22 33]
 [44 55 66]]


## Concatenate von zwei zweidimensionalen Arrays an Axis 1
Wenn wir concatenate mit axis=1 durchführen, werden die Arrays "nebeneinandert" zusammengefügt. Das führt dazu, dass der sich Shape der Columns (Spalten) verändert, der Zeilenshape aber gleich bleibt. 
![title](explanation_numpy-concatenate-axis-1.webp)

In [14]:
arr1 = np.array([[1, 1, 1], [1, 1, 1]])
arr2 = np.array([[9, 9, 9], [9, 9, 9]])

arr3_y = np.concatenate((arr1, arr2), axis=0)
arr3_x = np.concatenate((arr1, arr2), axis=1)

print("Y / axis 0: ", '\n', arr3_y)
print("base Y: ", arr3_y.base)
print("-----------------------------")
print("X / axis 1: ", '\n', arr3_x)
print("base X: ", arr3_x.base)


# alternativa (vstack)
x_st = np.hstack([arr1, arr2])

# alternativa (vstack)
y_st = np.vstack((arr1, arr2))
print("alternativas: ")
print("-----------------------------")
print("vertical / y_st / axis 0: ", '\n', y_st)
print("-----------------------------")
print("horizontal / x_st / axis 1: ", '\n',x_st)
print("-----------------------------")


Y / axis 0:  
 [[1 1 1]
 [1 1 1]
 [9 9 9]
 [9 9 9]]
base Y:  None
-----------------------------
X / axis 1:  
 [[1 1 1 9 9 9]
 [1 1 1 9 9 9]]
base X:  None
alternativas: 
-----------------------------
vertical / y_st / axis 0:  
 [[1 1 1]
 [1 1 1]
 [9 9 9]
 [9 9 9]]
-----------------------------
horizontal / x_st / axis 1:  
 [[1 1 1 9 9 9]
 [1 1 1 9 9 9]]
-----------------------------


## Vektor und Matrix via vstack zu einem mehrdimensionalen Array zusammenfügen
Um Arrays mit `concatenate` zu verbinden, müssen sie die gleichen Dimensionen haben. Somit lässt sich also kein ein- und mehrdimensionaler Array verbinden. Dazu gibt es die Methode `vstack`. vstack steht für vertikal Stapeln. 

Im Falle von vstack muss nur gegeben sein, dass beide Arrays die gleiche Anzahl an Spalten haben. Natürlich lassen sich auch zwei mehrdimensionale Arrays mit vstack verbinden.

In [9]:
arr1 = np.array([1, 1, 1])
arr2 = np.array([[9, 9, 9], [9, 9, 9]])

print(np.vstack((arr1, arr2)))


[[1 1 1]
 [9 9 9]
 [9 9 9]]


## Zwei Matritzen via hstack zu einem mehrdimensionalen Array zusammenfügen
Um Arrays mit `concatenate` zu verbinden, müssen sie die gleichen Dimensionen haben. Somit lässt sich also kein ein- und mehrdimensionaler Array verbinden. Dazu gibt es die Methode `hstack`. hstack steht für horizontal Stapeln. 

Im Falle von vstack muss nur gegeben sein, dass beide Arrays die gleiche Anzahl an Zeilen haben. 

In [20]:
# zwei Arrays mit shape 2,1 und 2,3
arr1 = np.array([[1], [1]])
arr2 = np.array([[9, 9, 9], [9, 9, 9]])


## Aufgabe

## Aufgabe

Ein Unternehmen verwaltet den Bestand von 6 Produkten in einem Zentrallager und zwei Filialen. Die Bestandsdaten liegen als 1D-Array vor und sollen für eine bessere Analyse umgeformt werden.

1. Reshape das gegebene 1D-Array in eine 3×6-Matrix, sodass jede Zeile einem Lagerstandort entspricht (Zentrallager, Filiale 1, Filiale 2).
2. Extrahiere (Slice) aus der Matrix die Bestände der ersten 3 Produkte für alle Standorte.
3. Füge neue Produkte für zwei neue Filialen (3 und 4) der ursprünglichen stock-Matrix hinzu. Nutze dazu vstack. Speichere das Ergebnis in der Variable final_stock_matrix.



Das Ergebnis von final_stock_matrix sieht am Ende so aus:

[[100, 150,  80, 200,  50,  90],     
       [ 60, 120,  70, 100,  30,  50],       
       [ 40, 110,  60,  80,  20,  30],         
       [ 55, 130,  75,  95,  35,  60],         
       [ 45, 100,  65,  85,  25,  40]]

2. Das Slicing der Produkt sieht so aus:

        [[100, 150,  80],     
        [ 60, 120,  70],       
        [ 40, 110,  60]]     

In [30]:
import numpy as np

# 1D-Array mit den Beständen für 3 Standorte (6 Produkte pro Standort)
stock = np.array([100, 150, 80, 200, 50, 90,   # Zentrallager
                  60, 120, 70, 100, 30, 50,    # Filiale 1
                  40, 110, 60, 80, 20, 30])    # Filiale 2

print("Stock Brutto: \n", stock)
# 1. Reshape in eine 3x6-Matrix (Zeilen: Standorte, Spalten: Produkte)
reschaped_stock = np.reshape(stock, (3, 6))
print("RS: \n", reschaped_stock)

# 2. Slicing: Extrahiere die ersten 3 Produkte für alle Standorte (Ergebnis wird nicht weiter benötigt)
extract_1 = reschaped_stock[:3, :3]
print("Extract 1: \n", extract_1)

# 3. Simulierte Lieferung für zwei neue Filialen (2x6-Matrix)
new_delivery = np.array([[55, 130, 75, 95, 35, 60],  # Filiale 3
                         [45, 100, 65, 85, 25, 40]]) # Filiale 4

final_stock_matrix = np.concatenate((reschaped_stock, new_delivery), axis=0)
print("Final Stock Matrix: \n", final_stock_matrix)

Stock Brutto: 
 [100 150  80 200  50  90  60 120  70 100  30  50  40 110  60  80  20  30]
RS: 
 [[100 150  80 200  50  90]
 [ 60 120  70 100  30  50]
 [ 40 110  60  80  20  30]]
Extract 1: 
 [[100 150  80]
 [ 60 120  70]
 [ 40 110  60]]
Final Stock Matrix: 
 [[100 150  80 200  50  90]
 [ 60 120  70 100  30  50]
 [ 40 110  60  80  20  30]
 [ 55 130  75  95  35  60]
 [ 45 100  65  85  25  40]]
