# Broadcasting
El broadcasting en NumPy permite operaciones aritméticas entre matrices de diferentes formas adaptando automáticamente las matrices más pequeñas a las más grandes. Una dimensión de 1 se "estirará" para permitir la operación. Esto ahorra tiempo y memoria de Numpy sin crear copias innecesarias de los datos.

![title](broadcasting_1.png)

In [2]:
"""import numpy as np"""

In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([2])

result = a * b

x = a * 2
print("a * 2 = ", x)
print("a * b = ",result)

a * 2 =  [2 4 6]
a * b =  [2 4 6]


## 1) Agregar matrices con diferentes shape
Los arrays se pueden agregar entre sí si tienen a) el mismo shape o b) es uno de los shapes 1.

Ellipsis

## 2) Skalar-Multiplikation
Escalar a Array-Broadcasting: El escalador se amplía a toda la forma del array.

$a = 3$

$ M = \left( \begin{matrix} 4 & 2 \\ 3 & 5 \\ 2 & 9 \end{matrix} \right) \cdot a = \left( \begin{matrix} 12 & 6 \\ 9 & 15 \\ 6 & 27 \end{matrix} \right) $

In [2]:
M = np.array([[4, 2], [3, 5], [2, 9]])
M * 3

Ellipsis

## Tarea de ejercicio: Conversión de temperatura para varias ciudades

Las temperaturas medias diarias (en °C) para varias ciudades durante una semana en un array 2D. Tu tarea es convertir estas temperaturas a Fahrenheit utilizando Broadcasting.

In [3]:
import numpy as np

# Temperaturen in Grad Celsius für 4 Städte über 7 Tage
temperatures_celsius = np.array([
    [15, 17, 20, 21, 19, 18, 16],  # Stadt 1
    [10, 12, 15, 14, 13, 11, 9],   # Stadt 2
    [25, 27, 28, 29, 30, 26, 24],  # Stadt 3
    [5, 7, 10, 12, 8, 6, 4]        # Stadt 4
])

# TODO: Konvertiere die Temperaturen in Fahrenheit
# Formel: Fahrenheit = Celsius * 9/5 + 32



### Erwartete Ausgabe

Temperaturen in Fahrenheit:

[[59.   62.6  68.   69.8  66.2  64.4  60.8]   
 [50.   53.6  59.   57.2  55.4  51.8  48.2]     
 [77.   80.6  82.4  84.2  86.   78.8  75.2]     
 [41.   44.6  50.   53.6  46.4  42.8  39.2]]    