# Boolsche Vergleichsoperatoren

Boolsche Masken in NumPy sind Arrays aus True- und False-Werten, die verwendet werden, um bestimmte Elemente eines Arrays zu filtern oder zu bearbeiten. Sie ermöglichen es, Operationen nur auf die Elemente anzuwenden, die einer bestimmten Bedingung entsprechen. Boolsche Masken sind besonders nützlich für schnelle, vektorisierten Abfragen, wie z.B. das Filtern von Werten größer als ein bestimmter Schwellenwert.

## Boolsche Vergleiche, boolsche Serie

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
THRESHOLD = 3

result = [elemento > THRESHOLD for elemento in [1, 2, 3, 4, 5]]
print("resultado largo", result)

result_corto = a > THRESHOLD
print("resultado corto", result_corto)

resultado largo [False, False, False, True, True]
resultado corto [False False False  True  True]


### Und Oder mit binären Operatoren
Für die Und-Bedingung in NumPy wird das kaufmännische Und (&) verwendet, das normalerweise für bitweise Operationen genutzt wird. Ebenso kommt das Pipe-Symbol (|) zum Einsatz, das für das bitweise Oder steht. Beide Operatoren werden in Kombination mit booleschen Masken verwendet, um logische Bedingungen effizient auszudrücken.

### ODER

In [4]:
# bei einer Oder-Verknüpfung die Klammern nicht vergessen! Ansonsten Fehler.

result = (a > 4) | (a < 2)
print(result)

[ True False False False  True]


### UND

In [3]:
# bei einer Und-Verknüpfung die Klammern nicht vergessen! Ansonsten Fehler.

result = (a > 4) & (a < 2)
print(result)

[False False False False False]


In [10]:
result = (a == 3)
result

array([False, False,  True, False, False])

### NOT

In NumPy wird die Negation einer booleschen Maske oder eines booleschen Arrays mit der Funktion np.logical_not() oder dem Tilde-Operator (~) umgesetzt.

In [5]:
# Negation
a = np.array([1, 2, 3, 4, 5])

mask = a > 3
negated_mask = ~mask
print("mask: ", mask)
print("negate: ", negated_mask)



mask:  [False False False  True  True]
negate:  [ True  True  True False False]


## All und Any
um zu prüfen, ob alle Werte in einer boolschen Serie wahr sind, können wir die `all-Funktion`nutzen. `Any`hingegen prüft, ob zumindest ein Wert in der Serie wahr ist (vgl. den Python-Funktionen all und any). Die Numpy-Pendants sind allerdings deutlich schneller.

In [8]:
# sind alle Werte wahr?

# -------- python --------
x = 3

if x > 3 and x < 3 and x in [1, 2, 3]:
    print("si senhor")

if all([x > 3,
        x < 3,
        x in [1, 2, 3]]):
    print("con todos los valores verdaderos")


# -------- NUMPY --------
M = np.random.random(size=(2,3))
values = np.any(M < 0.4)
print(M)
print(values)


In [6]:
# ist zumindest ein Wert wahr?

# Boolsches Indexing
Boolsche Serien lassen sich zum Indizieren von Numpy Arrays verwenden

In [9]:
np.random.seed(42)
M = np.random.random(size=(1, 3))

maske = M < 0.5
M, M[maske]

(array([[0.37454012, 0.95071431, 0.73199394]]), array([0.37454012]))

In [19]:
# Mehrdimensionale Arrays verlieren generell beim Multi-Indexing den Ursprungs-Shape

X = np.arange(1, 11).reshape((2, -1))
X_filtered = X[(X < 3) | (X > 8)]
print("X: ", X)
print("------")
# funciona como una especie de filtro
print("X-filtered: ", X_filtered)


X:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
------
X-filtered:  [ 1  2  9 10]


## Aufgabe

Du hast die Niederschlagsmengen (in mm) für jeden Tag eines Monats gegeben und sollst mehrere Bedingungen mit booleschen Masken kombinieren.

- a) Bestimme die Tage, an denen der Niederschlag mehr als 5 mm und weniger als 20 mm betrug.
- b) Bestimme die Tage, an denen der Niederschlag entweder 0 mm (kein Regen) oder mehr als 50 mm (starker Regen) betrug.
- c) Berechne den durchschnittlichen Niederschlag der Tage, an denen die Niederschlagsmenge zwischen 5 mm und 20 mm lag.
    

In [28]:
import numpy as np

# Niederschlagsmengen in mm für 30 Tage eines Monats
rainfall = np.array([
    0, 12, 5, 0, 18, 25, 0, 60, 55, 10, 
    6, 0, 15, 22, 5, 7, 0, 50, 52, 3, 
    8, 20, 30, 0, 12, 15, 0, 9, 45, 0
])

# TODO 1: Erstelle eine Maske für Niederschlag > 5 mm und < 20 mm
mask_between_5_and_20 = (rainfall > 5) & (rainfall < 20)
mask_between_5_and_20_b = (rainfall >= 5) & (rainfall <= 20)

# TODO 2: Erstelle eine Maske für Niederschlag == 0 mm ODER > 50 mm
mask_no_rain_or_heavy_rain = (rainfall == 0) | (rainfall > 50)

# TODO 3: Berechne den Durchschnitt der Niederschläge zwischen 5 mm und 20 mm
average_rainfall_between_5_and_20 = rainfall[ mask_between_5_and_20_b].mean()
# malos datos

# Ausgabe der Ergebnisse
print("1. Tage mit Niederschlag zwischen 5 und 20 mm:")
print(rainfall[mask_between_5_and_20])

print("\n2. Tage ohne Regen oder mit starkem Regen (> 50 mm):")
print(rainfall[mask_no_rain_or_heavy_rain])

print("\n3. Durchschnittlicher Niederschlag (5-20 mm):")
print(average_rainfall_between_5_and_20)


1. Tage mit Niederschlag zwischen 5 und 20 mm:
[12 18 10  6 15  7  8 12 15  9]

2. Tage ohne Regen oder mit starkem Regen (> 50 mm):
[ 0  0  0 60 55  0  0 52  0  0  0]

3. Durchschnittlicher Niederschlag (5-20 mm):
10.923076923076923


### Erwartet Ergebnisse

Tage mit Niederschlag zwischen 5 mm und 20 mm:     
[12, 18, 10, 6, 15, 7, 8, 12, 15, 9]   

Tage ohne Regen (0 mm) oder mit starkem Regen (> 50 mm):     
[0, 0, 0, 60, 55, 0, 50, 52, 0, 0, 0, 0]    

Durchschnittlicher Niederschlag der Tage zwischen 5 mm und 20 mm:   
11.2 mm 